worker_processes 1;

events {
    worker_connections 1024;
}

http {
    sendfile on;

    upstream auth_service {
        server auth:8000;
    }

    upstream documents_service {
        server documents:8000;
    }

    upstream agent_service {
        server agent:8000;
    }

    upstream billing_service {
        server billing:8000;
    }

    server {
        listen 80;
        server_name api.seu-dominio.com;

        return 301 https://$host$request_uri;
    }
}
